apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10
          #          livenessProbe:
          #            httpGet:
          #              path: /healthz
          #              port: 8080
          #            initialDelaySeconds: 30
          #            periodSeconds: 10
          #            failureThreshold: 3
          #            timeoutSeconds: 1
          #            successThreshold: 1
          image: "loxt/hello-go:latest"
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/orders"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-orders
            items:
              - key: orders
                path: "orders.txt"
#          env:
#            - name: "NAME"
#              valueFrom:
#                configMapKeyRef:
#                  name: goserver-env
#                  key: NAME
#            - name: "AGE"
#              valueFrom:
#                configMapKeyRef:
#                  name: goserver-env
#                  key: AGE
