apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "loxt/hello-go:v5"
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/orders"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-orders
            items:
              - key: orders
                path: "orders.txt"
#          env:
#            - name: "NAME"
#              valueFrom:
#                configMapKeyRef:
#                  name: goserver-env
#                  key: NAME
#            - name: "AGE"
#              valueFrom:
#                configMapKeyRef:
#                  name: goserver-env
#                  key: AGE
