apiVersion: v1
kind: Service
metadata:
  name: goserver-service
  labels:
    app: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - name: goserver-service
      port: 8080
      nodePort: 30080