apiVersion: v1
kind: Service
metadata:
  name: goserver-service
  labels:
    app: goserver-service
spec:
  selector:
    app: goserver-service
  type: ClusterIP
  ports:
    - name: goserver-service
      port: 8080
      targetPort: 8080
      protocol: TCP
